include:
  - board: lpgalaxy_blank_slate
  - board: lpgalaxy_blank_slate
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: lpgalaxy_blank_slate-studio
  - board: lpgalaxy_blank_slate
    shield: settings_reset
